// <auto-generated />
namespace EncurtadorUrl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddHitsInUrlControl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHitsInUrlControl));
        
        string IMigrationMetadata.Id
        {
            get { return "201712150047536_AddHitsInUrlControl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
